# Generated by Django 3.2.13 on 2022-05-29 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_rm_unused_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('strategy_name', models.CharField(choices=[('SMA', 'Средняя скользяшка'), ('RSI', 'RSI')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('strategy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.strategytype')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
