# Generated by Django 3.2.13 on 2022-05-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_strategy_strategytype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='strategy_id',
        ),
        migrations.AddField(
            model_name='strategy',
            name='strategy_name',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
